### ISSUE TITLE
TypeError: path.existsSync is not a function

### ISSUE THREAD

**Issue by naeplus** [rgarcia/dochub#48]
When I try to run node web.js it gives me following error:

```
TypeError: path.existsSync is not a function
```

PS. I run node web.js after running npm install.

**Comment by megirfanoff** [comment]
me too

**Comment by zhangkma** [comment]
E:\workspace\dochub>npm install
npm WARN dochub-backend@1.0.1 No repository field.
npm WARN dochub-backend@1.0.1 No license field.

E:\workspace\dochub>node web.js
E:\workspace\dochub\node_modules\requirejs\bin\r.js:2267
        if (path.existsSync(url)) {
                 ^

TypeError: path.existsSync is not a function
    at requirejsVars.nodeLoad.req.load (E:\workspace\dochub\node_modules\require
js\bin\r.js:2267:18)
    at resume (E:\workspace\dochub\node_modules\requirejs\bin\r.js:1282:65)
    at Object.require (E:\workspace\dochub\node_modules\requirejs\bin\r.js:1481:
25)
    at requirejs (E:\workspace\dochub\node_modules\requirejs\bin\r.js:1684:24)
    at Object.<anonymous> (E:\workspace\dochub\web.js:10:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
